### ISSUE TITLE
UnicodeEncodeError: 'gbk' codec can't encode character '\u2022' in position 472: illegal multibyte sequence

### ISSUE THREAD

**Issue by w5688414** [droneRL2020/sequence2sequence_attention#1]
my environment is ubuntu 16.04
I use python 3.5
but I got an error:
`UnicodeEncodeError: 'gbk' codec can't encode character '\u2022' in position 472: illegal multibyte sequence`

**Comment by droneRL2020** [comment]
Oh, I am currently working on this on window 10 anaconda virtual environment.
Will implement on Ubuntu 16.04 very soon. I also, got minor encoding errors as same as you.
